version: 2

sources:
  - name: google_ads
    database: bluwalk-data-warehouse
    tables:
      - name: ad_groups
      - name: ad_performance_reports
      - name: ads
      - name: campaign_performance_reports
      - name: campaigns