version: 2

sources:
  - name: bolt
    database: bluwalk-data-warehouse
    schema: bolt
    tables:
      - name: cron_config
      - name: daily_report_summary
      - name: daily_report_trips
      - name: driver_performance
      - name: expiring_documents
      - name: order_log
      - name: trips_history
      - name: vehicle_engagement
      - name: vehicle_documents

  - name: bolt_v2
    database: bluwalk-analytics-hub
    schema: raw
    tables:
      - name: src_bolt_organizations
        description: "Manually inserted and updated"
      - name: src_bolt_report_types
        description: "Manually inserted and updated"
      - name: src_bolt_driver_earnings
        description: "Inserted by a cloud function from Bolt Portal / API"
      - name: src_bolt_driver_engagement
        description: "Inserted by a cloud function from Bolt Portal / API"