version: 2

sources:
  - name: bolt
    database: bluwalk-data-warehouse
    schema: bolt
    tables:
      - name: cron_config
      - name: daily_report_summary
      - name: daily_report_trips
      - name: driver_engagement
      - name: driver_performance
      - name: earnings_history
      - name: expiring_documents
      - name: order_log
      - name: trips_history
      - name: vehicle_engagement
      - name: vehicle_documents