SELECT
    'e8d8ba0b559bd193d89e320f44686eee' partner_key,
    2 sales_partner_id,
    CAST(id AS INTEGER) document_id,
    TIMESTAMP_SECONDS(created) created_timestamp,
    TIMESTAMP_SECONDS(expires) expires_timestamp,
    TIMESTAMP_SECONDS(verified) verified_timestamp,
    CAST(isExpiryRequired AS BOOLEAN) isExpiryRequired,
    CAST(fileName AS STRING) fileName,
    CAST(originalFileName AS STRING) originalFileName,
    CAST(status	AS STRING) status,
    CAST(type AS STRING) type,
    CAST(documentTypeId AS INTEGER) documentTypeId,
    CAST(source AS STRING) source,
    CAST(documentTypeName AS STRING) documentTypeName,
    CAST(documentTypeDescription AS STRING) documentTypeDescription,
    CAST(canDelete AS BOOLEAN) canDelete,
    CAST(insuranceProviderId AS INTEGER) insuranceProviderId,
    CAST(isExpired AS BOOLEAN) isExpired,
    CAST(expiresInDays AS INTEGER) expiresInDays,

    CAST(uploadedId AS INTEGER) uploaded_document_id,
    TIMESTAMP_SECONDS(uploadedCreated) uploaded_created_timestamp,
    TIMESTAMP_SECONDS(uploadedExpires) uploaded_expires_timestamp,
    TIMESTAMP_SECONDS(uploadedVerified) uploaded_verified_timestamp,
    CAST(uploadedIsExpiryRequired AS BOOLEAN) uploaded_isExpiryRequired,
    CAST(uploadedFileName AS STRING) uploaded_fileName,
    CAST(uploadedOriginalFileName AS STRING) uploaded_originalFileName,
    CAST(uploadedStatus	AS STRING) uploaded_status,
    CAST(uploadedType AS STRING) uploaded_type,
    CAST(uploadedDocumentTypeId AS INTEGER) uploaded_documentTypeId,
    CAST(uploadedSource AS STRING) uploaded_source,
    CAST(uploadedDocumentTypeName AS STRING) uploaded_documentTypeName,
    CAST(uploadedDocumentTypeDescription AS STRING) uploaded_documentTypeDescription,
    CAST(uploadedCanDelete AS BOOLEAN) uploaded_canDelete,
    CAST(uploadedInsuranceProviderId AS INTEGER) uploaded_insuranceProviderId,
    CAST(uploadedIsExpired AS BOOLEAN) uploaded_isExpired,
    CAST(uploadedExpiresInDays AS INTEGER) uploaded_expiresInDays,

    CAST(docTypeId AS INTEGER) docTypeId,
    CAST(docTypeName AS STRING) docTypeName,
    CAST(docTypeTitle AS STRING) docTypeTitle,
    CAST(docTypeDescription	AS STRING) docTypeDescription,
    CAST(docTypeIsExpiryRequired AS BOOLEAN) docTypeIsExpiryRequired,
    CAST(docTypeIsRequired AS BOOLEAN) docTypeIsRequired,
    CAST(companyId AS INTEGER) companyId,
    CAST(carId AS INTEGER) carId,
    TIMESTAMP_MILLIS(loadTimestamp) extraction_timestamp

FROM {{ source('bolt', 'vehicle_documents') }}