SELECT
    'e8d8ba0b559bd193d89e320f44686eee' partner_key,
    2 sales_partner_id,
    CAST(company_id AS INTEGER) company_id,
    CAST(date AS DATE) date,
    CAST(id AS INTEGER) vehicle_id,
    CAST(model AS STRING) vehicle_model,
    CAST(year AS INTEGER) vehicle_year,
    CAST(reg_number AS STRING) vehicle_reg_number,
    CAST(color AS STRING) vehicle_color,
    CAST(car_transport_licence_number AS STRING) vehicle_car_transport_licence_number,
    CAST(car_transport_licence_expires AS TIMESTAMP) vehicle_car_transport_licence_expires,
    CAST(seats AS INTEGER) vehicle_seats,
    CAST(has_card_payment AS BOOLEAN) has_card_payment,
    CAST(phone AS STRING) phone,
    CAST(car_group_name AS STRING) car_group_name,
    CAST(status AS STRING) status,
    CAST(waiting_orders_seconds AS INTEGER) waiting_orders_seconds,
    CAST(has_order_seconds AS INTEGER) has_order_seconds,
    CAST(earnings_per_hour_gross AS NUMERIC) earnings_per_hour_gross,
    CAST(earnings_per_hour_net AS NUMERIC) earnings_per_hour_net,
    CAST(gross_revenue AS NUMERIC) gross_revenue,
    CAST(net_earnings AS NUMERIC) net_earnings,
    CAST(bonuses AS NUMERIC) bonuses,
    CAST(acceptance_rate AS NUMERIC) acceptance_rate,
    CAST(finished_orders AS INTEGER) finished_orders,
    CAST(rides_per_hour	AS NUMERIC) rides_per_hour,
    TIMESTAMP_MILLIS(load_timestamp) extraction_timestamp

FROM {{ source('bolt', 'vehicle_engagement') }}