{{ config(
    enabled = false
) }}

SELECT
  CAST(event_date AS DATE) event_date,
  TIMESTAMP_MICROS(event_timestamp) event_timestamp,
  TIMESTAMP_MICROS(user_first_touch_timestamp) user_first_touch_timestamp,
  is_active_user,
  user_id,
  user_pseudo_id,
  stream_id,
  platform,
  MAX(CASE WHEN param.key = 'key' THEN param.value.string_value ELSE NULL END) AS key,
  MAX(CASE WHEN param.key = 'content' THEN param.value.string_value ELSE NULL END) AS content,
  MAX(CASE WHEN param.key = 'source' THEN param.value.string_value ELSE NULL END) AS source,
  MAX(CASE WHEN param.key = 'medium' THEN param.value.string_value ELSE NULL END) AS medium,
  MAX(CASE WHEN param.key = 'campaign' THEN param.value.string_value ELSE NULL END) AS campaign,
  MAX(CASE WHEN param.key = 'ga_session_id' THEN param.value.int_value ELSE NULL END) AS ga_session_id,
  MAX(CASE WHEN param.key = 'campaign_id' THEN param.value.string_value ELSE NULL END) AS campaign_id,
  MAX(CASE WHEN param.key = 'page_location' THEN param.value.string_value ELSE NULL END) AS page_location,
  MAX(CASE WHEN param.key = 'page_title' THEN param.value.string_value ELSE NULL END) AS page_title,
  MAX(CASE WHEN param.key = 'page_referrer' THEN param.value.string_value ELSE NULL END) AS page_referrer,
  MAX(CASE WHEN param.key = 'ga_session_number' THEN param.value.int_value ELSE NULL END) AS ga_session_number,
  MAX(CASE WHEN param.key = 'batch_page_id' THEN param.value.int_value ELSE NULL END) AS batch_page_id,
  MAX(CASE WHEN param.key = 'term' THEN param.value.string_value ELSE NULL END) AS term,
  MAX(CASE WHEN param.key = 'batch_ordering_id' THEN param.value.int_value ELSE NULL END) AS batch_ordering_id,
  MAX(CASE WHEN param.key = 'session_engaged' THEN param.value.string_value ELSE NULL END) AS session_engaged,
  MAX(CASE WHEN param.key = 'engaged_session_event' THEN param.value.int_value ELSE NULL END) AS engaged_session_event,
  MAX(CASE WHEN param.key = 'entrances' THEN param.value.int_value ELSE NULL END) AS entrances,
  MAX(CASE WHEN param.key = 'ignore_referrer' THEN param.value.string_value ELSE NULL END) AS ignore_referrer,
  MAX(CASE WHEN param.key = 'gclid' THEN param.value.string_value ELSE NULL END) AS gclid,
  MAX(CASE WHEN param.key = 'form_destination' THEN param.value.string_value ELSE NULL END) AS form_destination,
  MAX(CASE WHEN param.key = 'form_length' THEN param.value.int_value ELSE NULL END) AS form_length,
  MAX(CASE WHEN param.key = 'form_id' THEN param.value.string_value ELSE NULL END) AS form_id,
  MAX(CASE WHEN param.key = 'engagement_time_msec' THEN param.value.int_value ELSE NULL END) AS engagement_time_msec,
  geo.city AS city,
  geo.country AS country,
  geo.region AS region,
  geo.sub_continent AS sub_continent,
  geo.continent AS continent,
  device.category AS device_category,
  device.mobile_brand_name AS mobile_brand_name,
  device.mobile_model_name AS mobile_model_name,
  device.mobile_marketing_name AS mobile_marketing_name,
  device.mobile_os_hardware_model AS mobile_os_hardware_model,
  device.operating_system AS operating_system,
  device.operating_system_version AS operating_system_version,
  device.vendor_id AS vendor_id,
  privacy_info.analytics_storage AS privacy_info_analytics_storage,
  privacy_info.ads_storage AS privacy_info_ads_storage,
  privacy_info.uses_transient_token AS privacy_info_uses_transient_token
FROM
  {{ ref('base_google_analytics_events') }},
  UNNEST(event_params) AS param
WHERE
  event_name = 'form_submit'
GROUP BY
  event_date,
  event_timestamp,
  user_first_touch_timestamp,
  is_active_user,
  user_id,
  user_pseudo_id,
  stream_id,
  platform,
  geo.city,
  geo.country,
  geo.region,
  geo.sub_continent,
  geo.continent,
  device.category,
  device.mobile_brand_name,
  device.mobile_model_name,
  device.mobile_marketing_name,
  device.mobile_os_hardware_model,
  device.operating_system,
  device.operating_system_version,
  device.vendor_id,
  privacy_info.analytics_storage,
  privacy_info_ads_storage,
  privacy_info_uses_transient_token
ORDER BY event_timestamp DESC