version: 2

sources:
  - name: odoo_realtime
    database: bluwalk-data-warehouse
    schema: odoo_realtime
    tables:
      - name: account_account
      - name: account_analytic_account
      - name: account_analytic_line
      - name: account_bank_statement_line
      - name: account_partial_reconcile
      - name: account_move_line
      - name: account_move
      - name: account_journal
      - name: account_payment
      - name: booking
      - name: close_period
      - name: contract_type_line
      - name: financial_document
      - name: financial_system
      - name: fleet_vehicle
      - name: fleet_vehicle_deal
      - name: fleet_vehicle_insurance
      - name: fleet_vehicle_log_contract
      - name: fleet_vehicle_cost
      - name: fleet_vehicle_model
      - name: fleet_vehicle_model_brand
      - name: fuel
      - name: fuel_card_log
      - name: fuel_card
      - name: hr_employee
      - name: hr_department
      - name: ir_translation
      - name: ir_act_report_xml
      - name: insurance_policy
      - name: insurance_policy_payment
      - name: insurance_policy_type
      - name: payment_profile
      - name: product_product
      - name: product_template
      - name: product_category
      - name: rate_base
      - name: rental_contract
      - name: res_country_city
      - name: res_country
      - name: res_partner
      - name: res_partner_bank
      - name: res_sales_partner
      - name: res_sales_partner_type
      - name: res_sales_partner_account
      - name: res_sales_partner_account_log
      - name: res_service_partner
      - name: res_service_partner_type
      - name: res_users
      - name: sale_order
      - name: sale_order_line
      - name: segment
      - name: support_stage
      - name: support_ticket
      - name: support_ticket_category
      - name: support_ticket_theme
      - name: transaction_account
      - name: transaction_category
      - name: transaction_group
      - name: transaction_line
      - name: trips
      - name: vehicle_category
      - name: vehicle_rental
      - name: voucher
      - name: voucher_type