version: 2

sources:
  - name: hubspot_drivfit
    schema: hubspot
    database: drivfit-data-warehouse
    tables:
      - name: contact
      - name: contact_company
      - name: company
      - name: deal
      - name: deal_contact
      - name: deal_pipeline
      - name: merged_deal
      - name: owner
      - name: users
      - name: team
      - name: ticket
      - name: ticket_pipeline_stage