version: 2

sources:
  - name: uber
    database: bluwalk-data-warehouse
    tables:
      - name: cron_config
      - name: driver_activity
      - name: driver_status
      - name: driver_performance
      - name: driver_performance_v2
      - name: driver_quality
      - name: payment_ledger
      - name: payments_order
      - name: payment_transactions
      - name: report_requests
      - name: vehicles
      - name: vehicle_compliance
      - name: vehicle_performance
      - name: trip_activity