version: 2

sources:
  - name: evio
    database: bluwalk-analytics-hub
    schema: source_evio
    tables:
      - name: src_evio_sessions
        description: "Inserted by a cloud function from Evio API"