version: 2

sources:
  - name: odoo_drivfit
    schema: odoo_drivfit
    database: bluwalk-data-warehouse
    tables:
      - name: account_analytic_account
      - name: account_move
      - name: booking
      - name: billable_item
      - name: fleet_vehicle
      - name: fleet_vehicle_cost
      - name: fleet_vehicle_deal
      - name: fleet_vehicle_insurance_claim
      - name: fleet_vehicle_insurance
      - name: fleet_vehicle_model_brand
      - name: fleet_vehicle_model
      - name: fleet_vehicle_log_contract
      - name: fleet_vehicle_log_repair
      - name: fleet_vehicle_odometer
      - name: fleet_vehicle_station
      - name: insurance_claim_repair_rel
      - name: lease_contract_condition
      - name: lease_contract
      - name: product_category
      - name: product_product
      - name: product_template
      - name: purchase_order_line
      - name: rate_base
      - name: rate_mileage
      - name: rental_contract
      - name: res_partner
      - name: res_country_city
      - name: res_country
      - name: vehicle_category