version: 2

sources:
  - name: mds
    database: bluwalk-data-warehouse
    tables:
      - name: reconciliation
  
  - name: mds_v2
    database: bluwalk-analytics-hub
    tables:
      - name: src_mds_documents