version: 2

sources:
  - name: aircall
    database: bluwalk-data-warehouse
    tables:
      - name: call_created
      - name: call_answered
      - name: call_ended
      - name: call_ringing_on_agent

  - name: aircall_v2
    database: bluwalk-data-warehouse
    tables:
      - name: call_created
      - name: call_answered
      - name: call_ended
      - name: call_ringing_on_agent
      - name: call_recording
  
  - name: aircall_v3
    database: bluwalk-data-warehouse
    tables:
      - name: call
      - name: numbers
      - name: users

  - name: analytics_249934410
    database: bluwalk-data-warehouse
    tables:
      - name: events_*

  - name: analytics_342899811
    database: bluwalk-data-warehouse
    tables:
      - name: events_*

  - name: analytics_323684004
    database: bluwalk-data-warehouse
    tables:
      - name: events_*

  - name: appmaker
    database: bluwalk-data-warehouse
    tables:
      - name: driver_ledger_table
      - name: driver_statement

  - name: bluwalk_website_prod
    database: bluwalk-data-warehouse
    tables:
      - name: account_created
      - name: application_submitted
      - name: nps_response_submitted

  - name: bolt
    database: bluwalk-data-warehouse
    tables:
      - name: cron_config
      - name: daily_report_summary
      - name: daily_report_trips
      - name: driver_engagement
      - name: driver_performance
      - name: earnings_history
      - name: expiring_documents
      - name: order_log
      - name: trips_history
      - name: vehicle_engagement
      - name: vehicle_documents

  - name: bp
    database: bluwalk-data-warehouse
    tables:
      - name: cards
      - name: invoice_transactions
      - name: transactions
      - name: transactions_v2
      - name: transactions_v3

  - name: circuit
    database: bluwalk-data-warehouse
    tables:
      - name: cron_config
      - name: drivers
      - name: plans

  - name: correos
    database: bluwalk-data-warehouse
    tables:
      - name: correos_daily_report

  - name: evio
    database: bluwalk-data-warehouse
    tables:
      - name: charging_sessions

  - name: reporting
    database: drivfit-analytics-hub
    tables:
      - name: fct_accounting_move_lines
      - name: fct_rental_bookings
      - name: fct_deals
      - name: dim_accounting_analytic_accounts
  
  - name: marts
    database: drivfit-analytics-hub
    tables:
      - name: rpt_bluwalk_vehicle_contracts
      - name: rpt_vehicle_current_status

  - name: drivfit
    database: bluwalk-data-warehouse
    tables:
      - name: customer_survey

  - name: facebook_pages
    database: bluwalk-data-warehouse
    tables:
      - name: daily_page_metrics_total
      - name: unique_daily_page_metrics_total

  - name: facebook_ads
    database: bluwalk-data-warehouse
    tables:
      - name: ads
      - name: ad_sets
      - name: campaigns
      - name: insights

  - name: flight_aware
    database: bluwalk-data-warehouse
    tables:
      - name: airports
      - name: scheduled_arrivals

  - name: free_now
    database: bluwalk-data-warehouse
    tables:
      - name: booking_history

  - name: gcloud
    database: bluwalk-data-warehouse
    tables:
      - name: cloudaudit_googleapis_com_data_access_*

  - name: generic
    database: bluwalk-data-warehouse
    tables:
      - name: address_geocoding
      - name: calendar
      - name: close_period_log
      - name: reporting_structure
      - name: zip_codes
      - name: zones

  - name: google_ads
    database: bluwalk-data-warehouse
    tables:
      - name: ad_groups
      - name: ad_performance_reports
      - name: ads
      - name: campaign_performance_reports
      - name: campaigns

  - name: google_workspace
    database: bluwalk-data-warehouse
    tables:
      - name: users

  - name: google_sheets
    database: bluwalk-data-warehouse
    tables:
      - name: ad_group_classification
      - name: churn_prevention
      - name: fin_month_closing
      - name: quarter_params
      - name: transaction_account_forwarding
      - name: user_own_vehicles
      - name: uncollectible_recovery

  - name: hubspot_drivfit
    schema: hubspot
    database: drivfit-data-warehouse
    tables:
      - name: deal

  - name: hubspot
    database: bluwalk-data-warehouse
    tables:
      - name: contact
      - name: deal
      - name: deal_contact
      - name: deal_pipeline
      - name: deal_pipeline_stage
      - name: deal_stage
      - name: engagement_email
      - name: merged_deal
      - name: owner
      - name: owner_team
      - name: property
      - name: property_option
      - name: team
      - name: team_user
      - name: ticket
      - name: ticket_contact
      - name: ticket_engagement
      - name: ticket_pipeline
      - name: ticket_pipeline_stage
      - name: users

  - name: drivfit_hubspot
    database: drivfit-data-warehouse
    schema: hubspot
    tables:
      - name: contact
      - name: deal
      - name: deal_contact
      - name: owner
      - name: team
      - name: team_user
      - name: ticket
      - name: ticket_contact
      - name: ticket_engagement
      - name: ticket_pipeline
      - name: ticket_pipeline_stage
      - name: users

  - name: instagram_business
    database: bluwalk-data-warehouse
    tables:
      - name: user_insights

  - name: mds
    database: bluwalk-data-warehouse
    tables:
      - name: receipts
      - name: reconciliation

  - name: mercadao
    database: bluwalk-data-warehouse
    tables:
      - name: account_status_log
      - name: availability
      - name: daily_order_summary
      - name: training_schedule
      - name: order_log
      - name: signup_status

  - name: monday
    database: bluwalk-data-warehouse
    tables:
      - name: issue_tracker_log
    
  - name: miio
    database: bluwalk-data-warehouse
    tables:
      - name: ev_transactions

  - name: odoo_realtime
    database: bluwalk-data-warehouse
    tables:
      - name: account_account
      - name: account_analytic_account
      - name: account_analytic_line
      - name: account_bank_statement_line
      - name: account_partial_reconcile
      - name: account_move_line
      - name: account_move
      - name: account_journal
      - name: account_payment
      - name: booking
      - name: close_period
      - name: contract_type_line
      - name: financial_document
      - name: financial_system
      - name: fleet_vehicle
      - name: fleet_vehicle_deal
      - name: fleet_vehicle_insurance
      - name: fleet_vehicle_log_contract
      - name: fleet_vehicle_cost
      - name: fleet_vehicle_model
      - name: fleet_vehicle_model_brand
      - name: fuel
      - name: fuel_card_log
      - name: fuel_card
      - name: hr_employee
      - name: hr_department
      - name: ir_translation
      - name: ir_act_report_xml
      - name: insurance_policy
      - name: insurance_policy_payment
      - name: insurance_policy_type
      - name: payment_profile
      - name: product_product
      - name: product_template
      - name: product_category
      - name: rate_base
      - name: rental_contract
      - name: res_country_city
      - name: res_country
      - name: res_partner
      - name: res_partner_bank
      - name: res_sales_partner
      - name: res_sales_partner_type
      - name: res_sales_partner_account
      - name: res_sales_partner_account_log
      - name: res_service_partner
      - name: res_service_partner_type
      - name: res_users
      - name: sale_order
      - name: sale_order_line
      - name: segment
      - name: support_stage
      - name: support_ticket
      - name: support_ticket_category
      - name: support_ticket_theme
      - name: transaction_account
      - name: transaction_category
      - name: transaction_group
      - name: transaction_line
      - name: trips
      - name: vehicle_category
      - name: vehicle_rental
      - name: voucher
      - name: voucher_type
  
  - name: odoo_drivfit
    schema: odoo
    database: drivfit-data-warehouse
    tables:
      - name: account_move
      - name: billable_item
      - name: fleet_vehicle
      - name: fleet_vehicle_cost
      - name: fleet_vehicle_deal
      - name: fleet_vehicle_model_brand
      - name: fleet_vehicle_model
      - name: fleet_vehicle_log_contract
      - name: res_partner

  - name: odoo_enterprise
    database: bluwalk-data-warehouse
    tables:
      - name: account_account
      - name: account_bank_statement_line
      - name: account_move
      - name: account_move_line
      - name: account_journal
      - name: hr_department
      - name: hr_employee
      - name: res_company
      - name: res_partner
      - name: res_partner_bank
      

  - name: prio
    database: bluwalk-data-warehouse
    tables:
      - name: ev_transactions
      - name: invoice_transactions
      - name: ff_invoice_transactions

  - name: predict_hq
    database: bluwalk-data-warehouse
    tables:
      - name: entities
      - name: events
      - name: impact_patterns

  - name: repsol
    database: bluwalk-data-warehouse
    tables:
      - name: invoice_transactions

  - name: snapshots
    schema: snapshots
    tables:
      - name: snap_odoo_statement_close

  - name: talkdesk
    database: bluwalk-data-warehouse
    tables:
      - name: calls
      - name: flows

  - name: tracker_logs
    database: bluwalk-data-warehouse
    tables:
      - name: close_period_log

  - name: uber
    database: bluwalk-data-warehouse
    tables:
      - name: cron_config
      - name: driver_activity
      - name: driver_status
      - name: trip_activity
      - name: driver_performance
      - name: driver_quality
      - name: payment_ledger
      - name: payments_order
      - name: payment_transactions
      - name: vehicles
      - name: vehicle_compliance

  - name: zendesk
    database: bluwalk-data-warehouse
    schema: zendesk
    description: "Status: Inactive. This source contains all Zendesk-related data, including support ticket information, user details, and satisfaction ratings."
    tables:
      - name: attachments
        description: "Contains metadata about file attachments within Zendesk tickets, such as content types, file names, and URLs."

      - name: group_memberships
        description: "Tracks associations between users and groups in Zendesk, detailing membership creation and updates."

      - name: groups
        description: "Details the groups created in Zendesk, including their names, creation, and update timestamps."

      - name: organizations
        description: "Lists all the organizations in Zendesk, along with related information like names, shared tickets, and comments."

      - name: satisfaction_ratings
        description: "Captures customer satisfaction ratings for tickets, including comments and the associated ticket and user IDs."

      - name: ticket_events
        description: "Logs ticket-related events, tracking status changes, assignments, tags, and satisfaction ratings."

      - name: ticket_fields
        description: "Defines custom fields within tickets, including descriptions, positions, and visibility settings."

      - name: ticket_forms
        description: "Stores Zendesk ticket form configurations, which determine the layout and fields of a ticket."

      - name: ticket_metrics
        description: "Records various metrics related to ticket handling and resolution, including wait times and resolution durations."

      - name: tickets
        description: "Main table containing tickets raised in Zendesk, their status, assignee, requester, and other key ticket details."

      - name: users
        description: "Contains details about users in Zendesk, including their roles, contact information, and activity status."
