version: 2

sources:

  - name: drivfit
    database: bluwalk-data-warehouse
    tables:
      - name: customer_survey

  - name: gcloud
    database: bluwalk-data-warehouse
    tables:
      - name: cloudaudit_googleapis_com_data_access_*

  - name: snapshots
    schema: snapshots
    tables:
      - name: snap_odoo_statement_close

  - name: tracker_logs
    database: bluwalk-data-warehouse
    tables:
      - name: close_period_log